// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ReactQueryApi.Models
{
    public partial class Product
    {
        public Guid Id { get; set; }
        public Guid? ProductGroupId { get; set; }
        public string Name { get; set; }
        public decimal? Price { get; set; }
        public decimal? Stock { get; set; }
        public Guid? CreatedUserId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? UpdatedUserId { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public bool? IsActive { get; set; }

        public virtual User CreatedUser { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
        public virtual User UpdatedUser { get; set; }
    }
}