// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ReactQueryApi.Models
{
    public partial class Role:IId
    {
        public Role()
        {
            UserRoles = new HashSet<UserRole>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string CreatedByUserId { get; set; }
        public string CreatedDate { get; set; }

        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}